
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage
	rm -rf wandb/*
	rm -rf logs/**

clean-logs: ## Clean logs
	rm -rf logs/**

clean-runs: ## be careful, this will erase all runs
	rm -rf logs/train/runs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train the model
	python src/train.py 

train_top10_baselines_cifar100:
	python src/train.py experiment=kd_baselines/cifar100/kd
	python src/train.py experiment=kd_baselines/cifar100/Fitnets
	python src/train.py experiment=kd_baselines/cifar100/AT
	python src/train.py experiment=kd_baselines/cifar100/NST
	python src/train.py experiment=kd_baselines/cifar100/SP
	python src/train.py experiment=kd_baselines/cifar100/RKD
	python src/train.py experiment=kd_baselines/cifar100/PKT
	#python src/train.py experiment=kd_baselines/cifar100/CC
	python src/train.py experiment=kd_baselines/cifar100/VID
	python src/train.py experiment=kd_baselines/cifar100/CRD
	python src/train.py experiment=kd_baselines/cifar100/CRD_KD
	#python src/train.py experiment=kd_baselines/cifar100/KDSVD

debug: ## Enter debugging mode with pdb
	#
	# tips:
	# - use "import pdb; pdb.set_trace()" to set breakpoint
	# - use "h" to print all commands
	# - use "n" to execute the next line
	# - use "c" to run until the breakpoint is hit
	# - use "l" to print src code around current line, "ll" for full function code
	# - docs: https://docs.python.org/3/library/pdb.html
	#
	python -m pdb src/train.py debug=default
