
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf wandb/*
	rm -rf logs/**

clean-runs: ## be careful, this will erase all runs
	rm -rf logs/train/runs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

download_data:
	python -m domainbed.scripts.download --data_dir=/srv/anisio/knowledge-distillation/data

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train the model
	python src/train.py 

train_erm_all: train_erm_colored_mnist train_erm_rotated_mnist train_erm_pacs train_erm_office_home train_erm_terra_incognita train_erm_domain_net 
#train_erm_vlcs train_erm_sviro train_erm_wilds_camelyon train_erm_wilds_fmow train_erm_celeba_blond train_erm_nico
#train_erm_imagenet_a train_erm_imagenet_r train_erm_imagenet_v2 

train_erm_colored_mnist:
	python src/train.py experiment=erm/train/erm_colored_mnist_irm 'model={test_envs: [0]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_colored_mnist_irm 'model={test_envs: [1]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_colored_mnist_irm 'model={test_envs: [2]}' 'datamodule={batch_size: 64}'

train_erm_rotated_mnist:
	python src/train.py experiment=erm/train/erm_rotated_mnist 'model={test_envs: [0]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_rotated_mnist 'model={test_envs: [1]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_rotated_mnist 'model={test_envs: [2]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_rotated_mnist 'model={test_envs: [3]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_rotated_mnist 'model={test_envs: [4]}' 'datamodule={batch_size: 64}'
	python src/train.py experiment=erm/train/erm_rotated_mnist 'model={test_envs: [5]}' 'datamodule={batch_size: 64}'
 
train_erm_vlcs:
	python src/train.py experiment=erm/train/erm_vlcs 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_vlcs 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_vlcs 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_vlcs 'model={test_envs: [3]}'

train_erm_pacs:
	python src/train.py experiment=erm/train/erm_pacs 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_pacs 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_pacs 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_pacs 'model={test_envs: [3]}'

train_erm_office_home:
	python src/train.py experiment=erm/train/erm_office_home 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_office_home 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_office_home 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_office_home 'model={test_envs: [3]}'

train_erm_terra_incognita:
	python src/train.py experiment=erm/train/erm_terra_incognita 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_terra_incognita 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_terra_incognita 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_terra_incognita 'model={test_envs: [3]}'

train_erm_domain_net:
	python src/train.py experiment=erm/train/erm_domain_net 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_domain_net 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_domain_net 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_domain_net 'model={test_envs: [3]}'
	python src/train.py experiment=erm/train/erm_domain_net 'model={test_envs: [4]}'
	python src/train.py experiment=erm/train/erm_domain_net 'model={test_envs: [5]}'

train_erm_sviro:
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [3]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [4]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [5]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [6]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [7]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [8]}'
	python src/train.py experiment=erm/train/erm_sviro 'model={test_envs: [9]}'

train_erm_wilds_camelyon:
	python src/train.py experiment=erm/train/erm_camelyon 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_camelyon 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_camelyon 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_camelyon 'model={test_envs: [3]}'

train_erm_wilds_fmow:
	python src/train.py experiment=erm/train/erm_fmow 'model={test_envs: [0]}'
	python src/train.py experiment=erm/train/erm_fmow 'model={test_envs: [1]}'
	python src/train.py experiment=erm/train/erm_fmow 'model={test_envs: [2]}'
	python src/train.py experiment=erm/train/erm_fmow 'model={test_envs: [3]}'

#train_erm_celeba_blond:
#	python src/train.py experiment=erm/train/erm_celeba_blond
#
#train_erm_nico:
#	python src/train.py experiment=erm/train/erm_nico
#
#train_erm_imagenet_a:
#	python src/train.py experiment=erm/train/erm_imagenet_a
#
#train_erm_imagenet_r:
#	python src/train.py experiment=erm/train/erm_imagenet_r
#
#train_erm_imagenet_v2:
#	python src/train.py experiment=erm/train/erm_imagenet_v2

train_top10_baselines_cifar100:
	python src/train.py experiment=kd_baselines/cifar100/kd
	python src/train.py experiment=kd_baselines/cifar100/Fitnets
	python src/train.py experiment=kd_baselines/cifar100/AT
	python src/train.py experiment=kd_baselines/cifar100/NST
	python src/train.py experiment=kd_baselines/cifar100/SP
	python src/train.py experiment=kd_baselines/cifar100/RKD
	python src/train.py experiment=kd_baselines/cifar100/PKT
	#python src/train.py experiment=kd_baselines/cifar100/CC
	python src/train.py experiment=kd_baselines/cifar100/VID
	python src/train.py experiment=kd_baselines/cifar100/CRD
	python src/train.py experiment=kd_baselines/cifar100/CRD_KD
	#python src/train.py experiment=kd_baselines/cifar100/KDSVD

debug: ## Enter debugging mode with pdb
	#
	# tips:
	# - use "import pdb; pdb.set_trace()" to set breakpoint
	# - use "h" to print all commands
	# - use "n" to execute the next line
	# - use "c" to run until the breakpoint is hit
	# - use "l" to print src code around current line, "ll" for full function code
	# - docs: https://docs.python.org/3/library/pdb.html
	#
	python -m pdb src/train.py debug=default
