_target_: src.models.litkd_teacher_ood_module.LitKDTeacherOODModule

results_dir: ${paths.output_dir}

eval_method:
  _target_: src.domainbed.model_selection.IIDAccuracySelectionMethod

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.MultiStepLR
#   _partial_: true
#   milestones: None
  # gamma: 0.1