_target_: src.datamodules.ood_datamodule.OODDataModule
data_dir: ${paths.data_dir}
dataset_name: None
test_envs: None
batch_size: 64
# train_val_split: [45000, 5000]
num_workers: 8
pin_memory: False
# distill: None
# mode: None
# nce_k: None
# is_sample: None
# percent: None